### PR TITLE
Port to net 5

### PR DESCRIPTION
**Pull request by RemiGC**
This is a port of the app to run on net 5.  

I ran the .[net upgrade assistant ](https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview)and cleaned up the result. Everything seems ok at first glance.

Let me know what you guys think.

### CODE REVIEW

**Comment by enohka** [comment]
Is this fully functional yet? Any concerns with dependencies like ziblib?

**Comment by RemiGC** [comment]
It's now added as a nuget package. Fonctionalities that use compression via `ZlibStream`  works.

`<PackageReference Include="Ionic.Zlib.Core" Version="1.0.0" />`

Every function in the app I know works. I don't think I know everything however.

There's debug only exception on runtime coming from xml serializers because of settings. Yyou can precompile an additional assembly to speed up xml serializer, if it's not there it fall back to reflection(I think). Never manage to make this works, on either 3.1, 5 or 6 preview. I assume that the speed trade off is ok since it's only for settings. 

If you have some tips on creating each files for the test assembly, I can make sure they all run.

**Comment by RemiGC** [comment]
I change the PR, to make the solution compile both net472 and net5. You can now switch between the two in VS. I added some tests to read data from red dragon & airbattle along a with .runsettings to specify the path to data folder.

**Comment by enohka** [comment]
I dont have the time to check this out right now but I love what you are doing thus Im going to merge the PR. Thanks for the contribution!

**Pull request merged**
